<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Calendrier</title>
    <style>
        body, html {
            margin: 0;
            padding: 0;
            height: 100%;
        }

        .calendar-section {
            background-size: cover;
            padding: 50px;
            text-align: center;
            height: 100vh;
        }

        .calendar {
            background: white;
            padding: 20px;
            width: 60%;
            margin: auto;
            border-radius: 10px;
        }

        .event-buttons {
            margin-top: 20px;
        }

        .event-buttons button {
            margin: 5px;
        }
    </style>
</head>

<body>
    <div class="calendar-section" style="background-image: linear-gradient(rgba(0, 0, 0, 0.5), rgba(0, 0, 0, 0.5)), url('https://saintjoseph972.com/wp-content/uploads/2023/01/322185555_5772923179453028_4657332333810531129_n.jpg');">
        <div class="calendar">
            <!-- Calendar HTML generated by a script or plugin -->
            <iframe frameborder="0" height="500px" width="100%" src="https://calendar.google.com/calendar/embed?src=kmaugee972%40gmail.com&ctz=America%2FMartinique"></iframe>
            <div class="event-buttons">
                <button onclick="location.href='add_event.php'">Ajouter</button>
                <button onclick="location.href='edit_event.php'">Modifier</button>
                <button onclick="location.href='delete_event.php'">Supprimer</button>
            </div>
            <div class="event-list">
                <!-- Here we will list the events using PHP -->
                <?php
                // Inclure la connexion à la base de données et la classe Event
                include_once 'database.php';
                include_once 'Event.php';

                // Instancier la base de données et la connexion
                $database = new Database();
                $db = $database->getConnection();

                // Instancier un objet Event
                $event = new Event($db);

                // Lire les événements
                $stmt = $event->read();

                // Afficher les événements
                while ($row = $stmt->fetch(PDO::FETCH_ASSOC)) {
                    extract($row);
                    echo "<div class='event'>";
                    echo "<h3>{$Titre}</h3>";
                    echo "<p>Date: {$Date}</p>";
                    echo "<p>Lieu: {$Lieu}</p>";
                    echo "<p>Description: {$Description}</p>";
                    echo "</div>";
                }
                ?>
            </div>
        </div>
    </div>
</body>

</html>